name: Run tests

on:
  workflow_dispatch:

  pull_request:
    branches: "main"

env:
  node_version: 24

jobs:
  validate:
    name: Validate code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: "pnpm"
      - run: pnpm install

      - name: Run tests
        run: pnpm run test
        
      - name: TypeScript check
        run: pnpm run typescript:check

      - name: Lint
        run: pnpm run lint

      - name: Format check
        run: pnpm run fmt:check
